using Utils.Expressions.Conversion;
using Utils.Expressions.Helpers;
using System.Reflection;

namespace Utils.Expressions.Mapping
{
    
    /// <summary>
    /// Class for configuring mapping options between source and target types
    /// </summary>
    public class MappingOptions
    {
        private readonly Type _sourceType;
        private readonly Type _targetType;
        private AutoMapping _autoMapping;
        private MappingPolicy _mappingPolicy;
        private readonly Dictionary<string, PropertyInfo> _sourceProperties;
        private readonly Dictionary<string, PropertyInfo> _targetProperties;

        // Seznam explicitně definovaných mapování
        private readonly Dictionary<string, List<PropertyMapping>> _explicitMappings = new();

        // Seznam automaticky generovaných mapování
        private Dictionary<string, PropertyMapping> _autoGeneratedMappings = new();

        public MappingOptions(Type sourceType, Type targetType)
        {
            _sourceType = sourceType;
            _targetType = targetType;
            _autoMapping = AutoMapping.ExactMatch;
            _mappingPolicy = MappingPolicy.Convertible;
            _sourceProperties = GetProperties(sourceType);
            _targetProperties = GetProperties(targetType);
        }

        public MappingOptions(Type sourceType, Type targetType, IEnumerable<PropertyMapping> explicitMappings,
            AutoMapping autoMapping = AutoMapping.ExactMatch, MappingPolicy mappingPolicy = MappingPolicy.Convertible)
            : this(sourceType, targetType)
        {
            _autoMapping = autoMapping;
            _mappingPolicy = mappingPolicy;
            AddMappings(explicitMappings);
        }

        public AutoMapping AutoMapping => _autoMapping;
        public MappingPolicy MappingPolicy => _mappingPolicy;
        public IReadOnlyDictionary<string, List<PropertyMapping>> ExplicitMappings => _explicitMappings;

        /// <summary>
        /// Adds one or more explicit mappings
        /// </summary>
        public void AddMapping(PropertyMapping mapping)
        {
            if (!mapping.Validate(_sourceType, _targetType))
            {
                throw new ArgumentException($"Invalid mapping to property '{mapping.TargetName}'");
            }

            if (!_explicitMappings.ContainsKey(mapping.TargetName))
            {
                _explicitMappings[mapping.TargetName] = new List<PropertyMapping>();
            }

            _explicitMappings[mapping.TargetName].Add(mapping);
        }

        /// <summary>
        /// Adds multiple explicit mappings at once
        /// </summary>
        public void AddMappings(IEnumerable<PropertyMapping> mappings)
        {
            foreach (var mapping in mappings)
            {
                AddMapping(mapping);
            }
        }

        /// <summary>
        /// Removes mapping for the given target property
        /// </summary>
        public void RemoveMapping(string targetPropertyName)
        {
            _explicitMappings.Remove(targetPropertyName);
        }

        /// <summary>
        /// Sets the automatic mapping mode
        /// </summary>
        public void SetAutoMapping(AutoMapping autoMapping)
        {
            _autoMapping = autoMapping;
            RegenerateAutoMappings();
        }

        /// <summary>
        /// Sets the mapping policy
        /// </summary>
        public void SetPolicy(MappingPolicy mappingPolicy)
        {
            _mappingPolicy = mappingPolicy;
            RegenerateAutoMappings();
        }

        /// <summary>
        /// Creates the final mapping list combining explicit and automatic mappings
        /// </summary>
        public IReadOnlyDictionary<string, PropertyMapping> CreateFinalMappings()
        {
            RegenerateAutoMappings();

            var finalMappings = new Dictionary<string, PropertyMapping>();

            // Nejprve přidáme automatická mapování
            foreach (var autoMapping in _autoGeneratedMappings)
            {
                finalMappings[autoMapping.Key] = autoMapping.Value;
            }

            // Poté přidáme explicitní mapování, která přepíší automatická
            foreach (var explicitMappingPair in _explicitMappings)
            {
                // Pro každou target vlastnost použijeme první validní explicitní mapování
                var validMapping = explicitMappingPair.Value.FirstOrDefault(m => m.Validate(_sourceType, _targetType));
                if (validMapping != null)
                {
                    finalMappings[explicitMappingPair.Key] = validMapping;
                }
            }

            return finalMappings;
        }

        private Dictionary<string, PropertyInfo> GetProperties(Type type)
        {
            return type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                      .Where(p => p.CanRead && !p.GetMethod.IsStatic)
                      .ToDictionary(p => p.Name);
        }

        private void RegenerateAutoMappings()
        {
            _autoGeneratedMappings.Clear();

            if (_autoMapping == AutoMapping.None)
                return;

            foreach (var targetProperty in _targetProperties.Values)
            {
                // Přeskočíme vlastnosti, které už mají explicitní mapování
                if (_explicitMappings.ContainsKey(targetProperty.Name))
                    continue;

                if (!targetProperty.CanWrite)
                    continue;

                PropertyMapping? autoMapping = null;

                // Pokusíme se najít odpovídající source vlastnost
                if (_sourceProperties.TryGetValue(targetProperty.Name, out var sourceProperty))
                {
                    // Zkontrolujeme, zda lze tyto vlastnosti mapovat podle politiky
                    if (CanMapProperties(sourceProperty, targetProperty))
                    {
                        autoMapping = new SimplePropertyMapping
                        {
                            SourceName = sourceProperty.Name,
                            TargetName = targetProperty.Name
                        };
                    }
                }

                // Pokud se podařilo vytvoříme auto mapování, přidáme ho
                if (autoMapping != null && autoMapping.Validate(_sourceType, _targetType))
                {
                    _autoGeneratedMappings[targetProperty.Name] = autoMapping;
                }
            }
        }

        private bool CanMapProperties(PropertyInfo sourceProperty, PropertyInfo targetProperty)
        {
            switch (_mappingPolicy)
            {
                case MappingPolicy.Strict:
                    return sourceProperty.PropertyType == targetProperty.PropertyType;

                case MappingPolicy.Implicit:
                    return ConversionHelper.CanConvertImplicitly(sourceProperty.PropertyType, targetProperty.PropertyType);

                case MappingPolicy.Convertible:
                    return ConversionHelper.IsTypeConvertible(sourceProperty.PropertyType, targetProperty.PropertyType);

                case MappingPolicy.Unrestricted:
                    return true;

                default:
                    return false;
            }
        }

        /// <summary>
        /// Creates a new MappingOptions for the reverse mapping direction
        /// </summary>
        public MappingOptions CreateReverseMappingOptions()
        {
            var reverseOptions = new MappingOptions(_targetType, _sourceType)
            {
                _autoMapping = _autoMapping,
                _mappingPolicy = _mappingPolicy
            };

            // Pokusíme se vytvořit zpětná mapování pro simple mappings
            foreach (var explicitMapping in _explicitMappings.Values.SelectMany(list => list))
            {
                if (explicitMapping is SimplePropertyMapping simpleMapping)
                {
                    var reverseMapping = new SimplePropertyMapping
                    {
                        SourceName = simpleMapping.TargetName,
                        TargetName = simpleMapping.SourceName
                    };

                    if (reverseMapping.Validate(_targetType, _sourceType))
                    {
                        reverseOptions.AddMapping(reverseMapping);
                    }
                }
                // Pro ostatní typy mapování musíme předat odpovědnost na uživatele
            }

            return reverseOptions;
        }
    }

}
